// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0m-SVYkw4i51MOdZBxV-9oKEySURwh4M',
    appId: '1:740392261000:web:492960da1d787aafe3163d',
    messagingSenderId: '740392261000',
    projectId: 'food-waste-game',
    authDomain: 'food-waste-game.firebaseapp.com',
    storageBucket: 'food-waste-game.appspot.com',
    measurementId: 'G-MTMLHYD172',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsYN0TUyzaVHHDv29G1TwbSFI35OAiBXo',
    appId: '1:740392261000:android:dbeeaeb31e68e89fe3163d',
    messagingSenderId: '740392261000',
    projectId: 'food-waste-game',
    storageBucket: 'food-waste-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ENf2Zt7qPRXPVjTW5Lz5zMbQcq_W6Kc',
    appId: '1:740392261000:ios:2ef7261a7ac92fc3e3163d',
    messagingSenderId: '740392261000',
    projectId: 'food-waste-game',
    storageBucket: 'food-waste-game.appspot.com',
    iosBundleId: 'com.example.foodWasteGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ENf2Zt7qPRXPVjTW5Lz5zMbQcq_W6Kc',
    appId: '1:740392261000:ios:e60b227f7c1b1498e3163d',
    messagingSenderId: '740392261000',
    projectId: 'food-waste-game',
    storageBucket: 'food-waste-game.appspot.com',
    iosBundleId: 'com.example.foodWasteGame.RunnerTests',
  );
}
